Week2 seungwoo
GDGoC-SCHU/2024-ai-study pull request #37
Opened 2024-12-13 08:31 UTC by Gonzo-Dev-lab

24-25 GDG 김승우
week2 스터디 과제 Pull request

2024-12-18 06:28 UTC, kimhamyong approved these changes
task3:

- 현재 파라미터 그리드에서 가능한 조합의 수가 많아져서 계산 시간이 너무 오래걸리고 있습니다!
GridSearchCV 대신 RandomizedSearchCV 사용: 무작위로 하이퍼파라미터를 탐색하는 방법을 추천드립니다.
- 부트스트래핑을 100번 반복하여 개별 DecisionTreeRegressor를 학습시키고 있는데, 이미 RandomForestRegressor는 내부적으로 부트스트래핑과 앙상블을 수행하므로 별도로 구현할 필요가 없습니다.
- make_moons 데이터셋은 이진 분류 문제입니다. 그러나 회귀 모델을 사용하고 있어 정확도가 낮게 나오고 있습니다.

수고하셨습니다.

2024-12-18 09:28 UTC, giyomdabin requested changes
task1, task2: 코랩에서 실행해본 결과, 코드가 수행되지 않습니다.

task1, task2 모두 특성 이름과 타깃 이름을 출력하는 과정에서 오류가 발생합니다.
문법을 다시 한 번 확인하신 후, 다시 업로드 해주세요!

감사합니다.

2024-12-20 08:07 UTC, Gonzo-Dev-lab commented
문법 문제 해결과 피드백 주신 부분 일부 수정 완료했습니다.

2024-12-20 14:35 UTC, giyomdabin commented
task1, task2: 확인한 결과, 모두 잘 수행하셨습니다. 수고하셨습니다!

2024-12-20 14:35 UTC, merged