Week2-huiju
GDGoC-SCHU/2024-ai-study pull request #42
Opened 2024-12-14 13:37 UTC by momiju

2024-12-17 06:07 UTC, kimhamyong requested changes
week1-huiju 폴더를 제외한 week2-huiju 폴더만 업로드 부탁드려요!

2024-12-21 10:52 UTC, kimhamyong approved these changes
task3: 잘 수행하셨습니다.

2024-12-21 11:39 UTC, giyomdabin requested changes
task1: 과제에 대한 출력 결과는 잘 나오지만, 정의하지 않은 model을 사용하고 있습니다. 확인 부탁드립니다!
task2: 빈 파일입니다. 다시 올려주세요.

2024-12-21 11:51 UTC, giyomdabin approved these changes
task2: 수고하셨습니다!

2024-12-21 11:51 UTC, merged