week2-gideon assignment
GDGoC-SCHU/2024-ai-study pull request #47
Opened 2024-12-17 06:44 UTC by gideonfrans22

늦게 제출한 점 사과드립니다. 앞으로는 제시간에 제출하도록 하겠습니다.

2024-12-18 06:30 UTC, kimhamyong approved these changes
task3: 잘 수행하셨습니다. 수고하셨습니다!

2024-12-18 09:19 UTC, giyomdabin requested changes
task1, task2: 주어진 과제에 대해서는 잘 수행하셨습니다!

다만, README.md 파일을 삭제하신 후, week2-gideon 폴더만 업로드해주세요!
수고하셨습니다, 감사합니다.

2024-12-19 06:38 UTC, gideonfrans22 commented
네 알겠습니다. 수정했습니다.

2024-12-20 10:26 UTC, kimhamyong approved these changes
task3: 잘 수행하셨습니다!

2024-12-20 14:16 UTC, giyomdabin commented
감사합니다. 수고하셨습니다!

2024-12-20 14:16 UTC, merged