[Week3] - Gideon
GDGoC-SCHU/2024-ai-study pull request #50
Opened 2024-12-20 14:30 UTC by gideonfrans22

3주차 과제 제출합니다.

2024-12-21 12:35 UTC, kimhamyong requested changes
week3-gideon 폴더만 업로드 부탁드립니다.

2024-12-21 15:48 UTC, gideonfrans22 commented
네, 수정했습니다.

2024-12-22 01:18 UTC, kimhamyong approved these changes
task1: 잘 수행하셨습니다.

- file.readlines()와 수동 반복으로 데이터를 숫자화하는 방식은 동작하지만 Pandas와 같은 라이브러리를 활용하면 더 간단하고 효율적으로 처리할 수 있습니다. 데이터의 각 범주를 data_types로 매핑하는 방식은 수동 작업을 필요로 하며 LabelEncoder를 사용하면 이 과정을 간소화할 수 있습니다.
- for line in lines는 데이터 크기가 작으면 괜찮지만 큰 파일에서는 비효율적일 수 있습니다. 대신 Pandas로 데이터를 읽고 apply 또는 내장된 범주형 변환 메서드를 사용하면 더 빠르고 깔끔하게 데이터를 처리할 수 있습니다.
- GridSearchCV를 통한 하이퍼파라미터 튜닝은 적절히 구현되었지만 RandomizedSearchCV와 같이 샘플링 기반 접근법을 사용하면 검색 시간이 줄어들 수 있습니다. 또한 param_grid를 외부 설정으로 분리하면 코드 유지보수가 쉬워집니다.

task2: 잘 수행하셨습니다.

- GridSearchCV를 통해 랜덤 포레스트의 하이퍼파라미터 튜닝을 수행한 점은 적절하지만, 데이터셋이 크거나 파라미터 범위가 넓을 경우 RandomizedSearchCV를 사용하면 시간이 절약될 수 있습니다. 또한, param_grid를 외부 설정으로 분리하면 유지보수가 쉬워집니다.

2024-12-22 13:09 UTC, giyomdabin approved these changes
task3: 잘 수행하셨습니다. 수고하셨습니다!

2024-12-22 13:09 UTC, merged