[Week3] - chaeryeong
GDGoC-SCHU/2024-ai-study pull request #51
Opened 2024-12-20 15:37 UTC by fud21

# task 1
: car_evaluation.csv 데이터셋을 활용하여 의사결정트리와 랜덤포레스트 알고리즘의 두 모델을 학습하고 성능을  비교한다. 

# task 2
: car_evaluation.csv 데이터셋을 PCA로 변환하고, 주성분 분석 결과를 시각화하고, PCA 적용 전후 랜덤포레스트(Random Forest) 모델의 성능을 비교한다.

# task 3_1
: 초승달 데이터셋(Make Moons)에서 DBSCAN을 사용해 군집을 생성하고 이상치를 탐지한다. 

# task 3_2
: 와인 품질 데이터셋에서 DBSCAN을 사용해 이상치를 탐지한다.

2024-12-21 12:34 UTC, kimhamyong requested changes
폴더만 업로드 부탁드립니다.

2024-12-22 13:11 UTC, giyomdabin approved these changes
task3: 잘 수행하셨습니다. 수고하셨습니다.

2024-12-22 15:13 UTC, kimhamyong requested changes
task1: task2 과제가 업로드 되었습니다. 다시 업로드 해주세요.

task2: 잘 수행하셨습니다.

- 현재 전체 데이터를 학습과 평가에 모두 사용하고 있습니다. train_test_split을 활용해 데이터를 학습용과 테스트용으로 분리하면 더 정확한 모델 평가가 가능합니다.
- n_components=2 대신 n_components=0.95를 설정하여 데이터의 95% 이상의 분산을 설명하는 주성분을 선택하면 성능 하락을 완화할 가능성이 있습니다.

2024-12-24 04:02 UTC, kimhamyong approved these changes
task1: 잘 수행하셨습니다.

2024-12-24 04:02 UTC, merged