[Week4] - sungmin
GDGoC-SCHU/2024-ai-study pull request #89
Opened 2024-12-28 13:30 UTC by csm3310

week4-sungmin

2024-12-28 14:34 UTC, kimhamyong requested changes
week4-sungmin 폴더만 업로드해주세요.

2024-12-28 15:17 UTC, giyomdabin approved these changes
task2: 주어진 과제를 잘 수행하셨습니다. 수고하셨습니다!

2024-12-30 10:10 UTC, kimhamyong approved these changes
task1: 잘 수행하셨습니다.

2024-12-30 10:10 UTC, kimhamyong commented on week4-sungmin/task1.py
> +        Dense(256, input_shape=(784,)),
task1:

현재 케라스에선 `Dense(256, input_shape=(784,))` 대신 `Input` 레이어를 사용하는 것이 더 권장되고 있습니다.
   ```python
   from tensorflow.keras.layers import Input
   model = Sequential([
       Input(shape=(784,)),
       Dense(256),
       ...
   ])
   ```

2024-12-30 10:10 UTC, kimhamyong commented on week4-sungmin/task1.py
> +history = model.fit(x_train, y_train, batch_size=64, epochs=5, validation_split=0.2)
task1: 

추가적으로, 학습 도중 검증 손실이 더 이상 감소하지 않을 때 학습을 조기 종료하도록 EarlyStopping 콜백을 추가하면 불필요한 에포크 실행을 방지할 수 있습니다. (필수 사항 X)

   ```python
from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)
history = model.fit(x_train, y_train, batch_size=64, epochs=50, validation_split=0.2, callbacks=[early_stopping])
   ```

2024-12-30 10:10 UTC, merged